import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {KOM_FACE_TEXTURE} from './assets/kom-face.js';
const stage=document.querySelector('#stage'),status=document.querySelector('#status'),speech=document.querySelector('#speech'),mic=document.querySelector('#mic'),poke=document.querySelector('#poke'),hit=document.querySelector('#hit');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x233331);
const camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,100);camera.position.set(0,1.9,8.6);camera.lookAt(0,1.35,0);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;stage.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffe9d1,0x34404a,2));const key=new THREE.DirectionalLight(0xffe2c2,3);key.position.set(3,7,5);key.castShadow=true;scene.add(key);scene.add(new THREE.DirectionalLight(0x9ac9ff,1.2));
const floor=new THREE.Mesh(new THREE.CircleGeometry(4.8,64),new THREE.MeshStandardMaterial({color:0x5b3b2b,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.15;floor.receiveShadow=true;scene.add(floor);
const avatar=new THREE.Group();avatar.position.y=-.15;scene.add(avatar);const body=new THREE.Group();body.position.y=.15;avatar.add(body);
const shirtMat=new THREE.MeshStandardMaterial({color:0xe8e8e3,roughness:.82}),skinMat=new THREE.MeshStandardMaterial({color:0xa86b43,roughness:.72}),darkMat=new THREE.MeshStandardMaterial({color:0x181818,roughness:.9}),shoeMat=new THREE.MeshStandardMaterial({color:0xe7e4dc,roughness:.8});
function capsule(r,d,mat){const m=new THREE.Mesh(new THREE.CapsuleGeometry(r,d,8,16),mat);m.castShadow=true;m.receiveShadow=true;return m}
const torso=capsule(.82,1.15,shirtMat);torso.scale.set(.9,1,.62);torso.position.y=.45;body.add(torso);const neck=capsule(.24,.22,skinMat);neck.position.y=1.35;body.add(neck);
const head=new THREE.Group();head.position.y=2.12;avatar.add(head);const headShell=new THREE.Mesh(new THREE.SphereGeometry(1.05,32,24),skinMat);headShell.scale.set(.98,1.08,.88);headShell.castShadow=true;head.add(headShell);
const faceTex=new THREE.TextureLoader().load(KOM_FACE_TEXTURE);faceTex.colorSpace=THREE.SRGBColorSpace;
const faceGeo=new THREE.PlaneGeometry(1.72,2.05,12,12),pos=faceGeo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,.11+.09*(1-Math.min(1,(x/.86)**2+(y/1.02)**2)))}faceGeo.computeVertexNormals();const face=new THREE.Mesh(faceGeo,new THREE.MeshStandardMaterial({map:faceTex,roughness:.78}));face.position.set(0,.02,.82);head.add(face);
const cap=new THREE.Mesh(new THREE.SphereGeometry(1.08,32,16,0,Math.PI*2,0,Math.PI*.55),new THREE.MeshStandardMaterial({color:0xf1f1ee,transparent:true,opacity:.38,roughness:.7}));cap.scale.set(1,.55,.9);cap.position.set(0,.85,0);head.add(cap);
for(const s of [-1,1]){const ear=new THREE.Mesh(new THREE.SphereGeometry(.23,20,16),skinMat);ear.scale.set(.65,1,.55);ear.position.set(s*.99,.15,0);head.add(ear)}
function limb(r,d,mat,x,y,z){const g=capsule(r,d,mat);g.position.set(x,y,z);body.add(g);return g}const armL=limb(.25,1.05,skinMat,-.98,.25,.03),armR=limb(.25,1.05,skinMat,.98,.25,.03);armL.rotation.z=-.12;armR.rotation.z=.12;
const handL=new THREE.Mesh(new THREE.SphereGeometry(.29,20,16),skinMat);handL.position.set(-1.03,-.42,.03);body.add(handL);const handR=handL.clone();handR.position.x=1.03;body.add(handR);
const legL=limb(.29,1,darkMat,-.43,-1.18,.02),legR=limb(.29,1,darkMat,.43,-1.18,.02);const shoeL=new THREE.Mesh(new THREE.SphereGeometry(.42,20,16),shoeMat);shoeL.scale.set(1.2,.55,1.55);shoeL.position.set(-.43,-1.92,.18);body.add(shoeL);const shoeR=shoeL.clone();shoeR.position.x=.43;body.add(shoeR);
const browL=new THREE.Mesh(new THREE.BoxGeometry(.38,.07,.05),darkMat);browL.position.set(-.36,.42,.89);browL.rotation.z=-.15;head.add(browL);const browR=browL.clone();browR.position.x=.36;browR.rotation.z=.15;head.add(browR);
const mouth=new THREE.Mesh(new THREE.SphereGeometry(.23,20,12),new THREE.MeshStandardMaterial({color:0x5c1e24}));mouth.scale.set(1,.28,.28);mouth.position.set(0,-.45,.9);head.add(mouth);
let action=0,actionT=0,talking=false,downX=0,downY=0,downAt=0;
function say(t){speech.textContent=t;speech.classList.remove('show');void speech.offsetWidth;speech.classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>speech.classList.remove('show'),1600)}
function react(type){action=type;actionT=0;say(type==='hit'?'OW!':'Hey!');status.textContent=type==='hit'?'Ouch!':'Poked'}
function pointerDown(e){downX=e.clientX;downY=e.clientY;downAt=performance.now()}
function pointerUp(e){const dx=e.clientX-downX,dy=e.clientY-downY;if(Math.hypot(dx,dy)>70&&Math.abs(dx)>Math.abs(dy))react('hit');else if(performance.now()-downAt<650)react('poke')}
stage.addEventListener('pointerdown',pointerDown);stage.addEventListener('pointerup',pointerUp);poke.onclick=()=>react('poke');hit.onclick=()=>react('hit');
let rec=null,chunks=[],stream=null;async function start(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status.textContent='Microphone not supported';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=repeat;rec.start();mic.classList.add('active');status.textContent='Listening…'}catch{status.textContent='Microphone permission denied'}}
function stop(){if(rec&&rec.state!=='inactive'){rec.stop();stream?.getTracks().forEach(t=>t.stop());mic.classList.remove('active');status.textContent='Repeating…'}}
async function repeat(){const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'}),url=URL.createObjectURL(blob),a=new Audio(url);a.playbackRate=1.2;talking=true;a.onended=()=>{talking=false;status.textContent='Ready';URL.revokeObjectURL(url)};try{await a.play()}catch{status.textContent='Tap mic again to play'}}
mic.addEventListener('pointerdown',e=>{e.preventDefault();start()});['pointerup','pointercancel','pointerleave'].forEach(v=>mic.addEventListener(v,e=>{e.preventDefault();stop()}));say('Hi!');
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033),t=clock.elapsedTime;body.position.y=.15+Math.sin(t*2)*.035;head.rotation.y=Math.sin(t*.7)*.025;head.rotation.z=Math.sin(t*.9)*.012;
if(talking){mouth.scale.y=.28+Math.abs(Math.sin(t*18))*.42;head.rotation.x=Math.sin(t*10)*.035;body.rotation.y=Math.sin(t*8)*.015}else mouth.scale.y=THREE.MathUtils.lerp(mouth.scale.y,.28,.15);
if(action){actionT+=dt;const p=Math.min(actionT/(action==='hit'?.62:.38),1),s=Math.sin(p*Math.PI);body.rotation.z=s*(action==='hit'?.18:.08);head.rotation.z=s*(action==='hit'?.24:-.18);head.rotation.x=s*.12;avatar.scale.set(1+s*.045,1-s*.07,1+s*.045);if(action==='hit'){armL.rotation.z=-.12-s*.55;armR.rotation.z=.12+s*.55}if(p>=1){action=0;avatar.scale.set(1,1,1);body.rotation.z=0;head.rotation.x=0;armL.rotation.z=-.12;armR.rotation.z=.12}}
renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
